export enum ModifyMode {
  EDIT = 'EDIT',
  CREATE = 'CREATE',
}

export enum RepositoryKey {
  RACERS = "RACERS",
  CATEGORIES_MAP = "CATEGORIES_MAP",
  STARTERS = "STARTERS",
  STARTER_NAME_LIST =  "STARTER_NAME_LIST",
  FINISHERS = "FINISHERS",
  FINISHERS_BY_CATEGORIES = "FINISHERS_BY_CATEGORIES",
  ANONS = "ANONS",
  FINISHER_NAME_LIST =  "FINISHER_NAME_LIST",
  CURRENT_RACER_INDEX = "CURRENT_RACER_INDEX",
  CURRENT_ANON_INDEX =  "CURRENT_ANON_INDEX",
  RACE_NAME =  "RACE_NAME",
  RACERS_DELTA = "RACERS_DELTA",
}

export enum RaceStatus {
  PREPARE = 'PREPARE',
  PAUSE = 'PAUSE',
  START = 'START',
  FINISH = 'FINISH',
  READY = 'READY',
}

export enum RaceType {
  ITT = 'ITT',
  GROUP = 'GROUP',
}
